/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as KaryawanRouteRouteImport } from './routes/karyawan/route'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminJualRouteImport } from './routes/admin/jual'
import { Route as AdminLaporanRouteImport } from './routes/admin/laporan'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminScanRouteImport } from './routes/admin/scan'
import { Route as AdminStokRouteImport } from './routes/admin/stok'
import { Route as AdminVerifikasiRouteImport } from './routes/admin/verifikasi'
import { Route as KaryawanIndexRouteImport } from './routes/karyawan/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerAbsensiRouteImport } from './routes/manager/absensi'
import { Route as ManagerKaryawanRouteImport } from './routes/manager/karyawan'
import { Route as ManagerLaporanRouteImport } from './routes/manager/laporan'
import { Route as TiketKodeRouteImport } from './routes/tiket/$kode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryawanRouteRoute = KaryawanRouteRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJualRoute = AdminJualRouteImport.update({
  id: '/jual',
  path: '/jual',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStokRoute = AdminStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVerifikasiRoute = AdminVerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => AdminRouteRoute,
} as any)
const KaryawanIndexRoute = KaryawanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KaryawanRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAbsensiRoute = ManagerAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerKaryawanRoute = ManagerKaryawanRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerLaporanRoute = ManagerLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const TiketKodeRoute = TiketKodeRouteImport.update({
  id: '/tiket/$kode',
  path: '/tiket/$kode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/karyawan': typeof KaryawanRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/verifikasi': typeof AdminVerifikasiRoute
  '/manager/absensi': typeof ManagerAbsensiRoute
  '/manager/karyawan': typeof ManagerKaryawanRoute
  '/manager/laporan': typeof ManagerLaporanRoute
  '/tiket/$kode': typeof TiketKodeRoute
  '/admin/': typeof AdminIndexRoute
  '/karyawan/': typeof KaryawanIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/verifikasi': typeof AdminVerifikasiRoute
  '/manager/absensi': typeof ManagerAbsensiRoute
  '/manager/karyawan': typeof ManagerKaryawanRoute
  '/manager/laporan': typeof ManagerLaporanRoute
  '/tiket/$kode': typeof TiketKodeRoute
  '/admin': typeof AdminIndexRoute
  '/karyawan': typeof KaryawanIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/karyawan': typeof KaryawanRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/kasir': typeof KasirRoute
  '/login': typeof LoginRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/verifikasi': typeof AdminVerifikasiRoute
  '/manager/absensi': typeof ManagerAbsensiRoute
  '/manager/karyawan': typeof ManagerKaryawanRoute
  '/manager/laporan': typeof ManagerLaporanRoute
  '/tiket/$kode': typeof TiketKodeRoute
  '/admin/': typeof AdminIndexRoute
  '/karyawan/': typeof KaryawanIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/karyawan'
    | '/manager'
    | '/kasir'
    | '/login'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin/verifikasi'
    | '/manager/absensi'
    | '/manager/karyawan'
    | '/manager/laporan'
    | '/tiket/$kode'
    | '/admin/'
    | '/karyawan/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kasir'
    | '/login'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin/verifikasi'
    | '/manager/absensi'
    | '/manager/karyawan'
    | '/manager/laporan'
    | '/tiket/$kode'
    | '/admin'
    | '/karyawan'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/karyawan'
    | '/manager'
    | '/kasir'
    | '/login'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin/verifikasi'
    | '/manager/absensi'
    | '/manager/karyawan'
    | '/manager/laporan'
    | '/tiket/$kode'
    | '/admin/'
    | '/karyawan/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KaryawanRouteRoute: typeof KaryawanRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  KasirRoute: typeof KasirRoute
  LoginRoute: typeof LoginRoute
  TiketKodeRoute: typeof TiketKodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karyawan': {
      id: '/karyawan'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof KaryawanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jual': {
      id: '/admin/jual'
      path: '/jual'
      fullPath: '/admin/jual'
      preLoaderRoute: typeof AdminJualRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stok': {
      id: '/admin/stok'
      path: '/stok'
      fullPath: '/admin/stok'
      preLoaderRoute: typeof AdminStokRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/verifikasi': {
      id: '/admin/verifikasi'
      path: '/verifikasi'
      fullPath: '/admin/verifikasi'
      preLoaderRoute: typeof AdminVerifikasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/karyawan/': {
      id: '/karyawan/'
      path: '/'
      fullPath: '/karyawan/'
      preLoaderRoute: typeof KaryawanIndexRouteImport
      parentRoute: typeof KaryawanRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/absensi': {
      id: '/manager/absensi'
      path: '/absensi'
      fullPath: '/manager/absensi'
      preLoaderRoute: typeof ManagerAbsensiRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/karyawan': {
      id: '/manager/karyawan'
      path: '/karyawan'
      fullPath: '/manager/karyawan'
      preLoaderRoute: typeof ManagerKaryawanRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/laporan': {
      id: '/manager/laporan'
      path: '/laporan'
      fullPath: '/manager/laporan'
      preLoaderRoute: typeof ManagerLaporanRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/tiket/$kode': {
      id: '/tiket/$kode'
      path: '/tiket/$kode'
      fullPath: '/tiket/$kode'
      preLoaderRoute: typeof TiketKodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminJualRoute: typeof AdminJualRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminScanRoute: typeof AdminScanRoute
  AdminStokRoute: typeof AdminStokRoute
  AdminVerifikasiRoute: typeof AdminVerifikasiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminJualRoute: AdminJualRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminScanRoute: AdminScanRoute,
  AdminStokRoute: AdminStokRoute,
  AdminVerifikasiRoute: AdminVerifikasiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface KaryawanRouteRouteChildren {
  KaryawanIndexRoute: typeof KaryawanIndexRoute
}

const KaryawanRouteRouteChildren: KaryawanRouteRouteChildren = {
  KaryawanIndexRoute: KaryawanIndexRoute,
}

const KaryawanRouteRouteWithChildren = KaryawanRouteRoute._addFileChildren(
  KaryawanRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerAbsensiRoute: typeof ManagerAbsensiRoute
  ManagerKaryawanRoute: typeof ManagerKaryawanRoute
  ManagerLaporanRoute: typeof ManagerLaporanRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerAbsensiRoute: ManagerAbsensiRoute,
  ManagerKaryawanRoute: ManagerKaryawanRoute,
  ManagerLaporanRoute: ManagerLaporanRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KaryawanRouteRoute: KaryawanRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  KasirRoute: KasirRoute,
  LoginRoute: LoginRoute,
  TiketKodeRoute: TiketKodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
