/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminJualRouteImport } from './routes/admin/jual'
import { Route as AdminLaporanRouteImport } from './routes/admin/laporan'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminScanRouteImport } from './routes/admin/scan'
import { Route as AdminStokRouteImport } from './routes/admin/stok'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJualRoute = AdminJualRouteImport.update({
  id: '/jual',
  path: '/jual',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScanRoute = AdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStokRoute = AdminStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kasir': typeof KasirRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kasir': typeof KasirRoute
  '/admin/jual': typeof AdminJualRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/scan': typeof AdminScanRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kasir'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kasir'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kasir'
    | '/admin/jual'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/scan'
    | '/admin/stok'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KasirRoute: typeof KasirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jual': {
      id: '/admin/jual'
      path: '/jual'
      fullPath: '/admin/jual'
      preLoaderRoute: typeof AdminJualRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scan': {
      id: '/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AdminScanRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stok': {
      id: '/admin/stok'
      path: '/stok'
      fullPath: '/admin/stok'
      preLoaderRoute: typeof AdminStokRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminJualRoute: typeof AdminJualRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminScanRoute: typeof AdminScanRoute
  AdminStokRoute: typeof AdminStokRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminJualRoute: AdminJualRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminScanRoute: AdminScanRoute,
  AdminStokRoute: AdminStokRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KasirRoute: KasirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
